### ISSUE TITLE
Many bugs when imported to Unity

### ISSUE THREAD

**Issue by gabrieltva** [loodakrawa/SpriterDotNet#71] opened 2016-10-17 16:16 UTC
Hi guys,

I am trying to import an animation to Unity, and in the 50% of the cases, it's fail.
Why this happen?

Here is an animation on the Spriter Pro, and the same in the Unity, after the import:
![out-17-2016 14-10-56](https://cloud.githubusercontent.com/assets/5474849/19445616/cb943200-9473-11e6-853d-598ed3eaf0cf.gif)

In Unity:
![out-17-2016 14-12-11](https://cloud.githubusercontent.com/assets/5474849/19445621/d5c9b556-9473-11e6-980b-111bda1cbd24.gif)

Is not only this animation that the problem occurred.

Can you help me?

**Comment by loodakrawa** [comment] 2016-10-18 03:15
Do you get any errors (in the console) during importing?
Do the SpriterDotNet unity examples (all of them) work on your machine?

**Comment by gabrieltva** [comment] 2016-10-18 15:54
No errors in console, and Yes, all examples work fine.
I don't know what do with that. Do you has a solution?
Have a file which I can configure before to import in Unity?

My Unity version is 5.4.0f3.

**Comment by loodakrawa** [comment] 2016-10-18 22:32
Can you upload the animation in question somewhere so I can take a look?

**Comment by gabrieltva** [comment] 2016-10-18 22:51
I can send in your email. What is your email?
If you don't send here, please send me to gabriel@omegga.com.br
Thanks.

**Comment by loodakrawa** [comment] 2016-10-19 01:06
Send it to: loodakrawa@gmail.com

**Comment by gabrieltva** [comment] 2016-10-19 13:55
sent!

**Comment by loodakrawa** [comment] 2016-10-26 02:27
Just to make it clear - the issue is the displaced sword trail? (At least that's the only one I see)

**Comment by gabrieltva** [comment] 2016-10-27 20:14
Yes, in this animation yes!

**Comment by loodakrawa** [comment] 2017-10-27 01:07
Closing this as I haven't been able to replicate this with any other instances. The next major version will be a big rewrite of most of the functionality anyway.

**Closed as completed by loodakrawa** 2017-10-27 01:07 UTC
Labels: wontfix, unity
